// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/transitions/v1/schedule.proto (package shedule, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetScheduleListRequest, GetScheduleListResponse, PlanExecutionRequest, ScheduleByIdRequest, ScheduleOperationStatusResponse, ScheduleRequest, ScheduleResponse } from "./schedule_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service shedule.ScheduleService
 */
export const ScheduleService = {
  typeName: "shedule.ScheduleService",
  methods: {
    /**
     * @generated from rpc shedule.ScheduleService.AddSchedule
     */
    addSchedule: {
      name: "AddSchedule",
      I: ScheduleRequest,
      O: ScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.UpdateSchedule
     */
    updateSchedule: {
      name: "UpdateSchedule",
      I: ScheduleRequest,
      O: ScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.DeleteSchedule
     */
    deleteSchedule: {
      name: "DeleteSchedule",
      I: ScheduleByIdRequest,
      O: ScheduleOperationStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.DisableSchedule
     */
    disableSchedule: {
      name: "DisableSchedule",
      I: ScheduleByIdRequest,
      O: ScheduleOperationStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.EnableSchedule
     */
    enableSchedule: {
      name: "EnableSchedule",
      I: ScheduleByIdRequest,
      O: ScheduleOperationStatusResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.GetSchedule
     */
    getSchedule: {
      name: "GetSchedule",
      I: ScheduleByIdRequest,
      O: ScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.GetScheduleBy
     */
    getScheduleBy: {
      name: "GetScheduleBy",
      I: GetScheduleListRequest,
      O: GetScheduleListResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc shedule.ScheduleService.PlanExecution
     */
    planExecution: {
      name: "PlanExecution",
      I: PlanExecutionRequest,
      O: ScheduleOperationStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

