// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file proto/transitions/v1/user.proto (package user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserRequest, GetUserResponse } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.UserService
 */
export const UserService = {
  typeName: "user.UserService",
  methods: {
    /**
     * @generated from rpc user.UserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

