services:
  local-postgres:
    image: postgres
    container_name: local-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_ds_db
      POSTGRES_USER: db_user
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6379:6379"
    command: --cluster_mode=emulated --lock_on_hashtags
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/dragonfly:/data

  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    environment:
      DATABASE_URL: postgresql://db_user:password@local-postgres:5432/app_ds_db?schema=public
    depends_on:
      - local-postgres
    links:
      - local-postgres

  all-apps-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: all-apps-dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - local-postgres
    links:
      - local-postgres
