apiVersion: batch/v1
kind: CronJob
metadata:
  name: master-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: master-cron-job
              image: distributet-scheduler-master-cron-job:local
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - bun run index.js
          restartPolicy: OnFailure
